name: poetry install
on: push
env:
  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
jobs:
  poetry_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install poetry
      - run: poetry install
