name: poetry install
on: push
jobs:
  poetry_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install gnome-keyring # Add the temporary solution
      - run: pip install poetry
      - run: poetry install
